#!/bin/sh
#
# https://learn.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-ubuntu
#
DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y install cloud-init gdisk netplan.io

# We need to ensure that old, installer-generated cloud-init configurations
# do not get resurrected like zombies
systemctl stop cloud-init

# Remove conflicting cloud-init files generated by the None datasource used by
# the installer. If this is not done, the Azure VM will not have a netword,
# among other things.
cloud-init clean --logs --seed
rm -rf /var/lib/cloud/
rm -f \
 /etc/cloud/cloud.cfg.d/90-installer-network.cfg \
 /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg \
 /etc/cloud/cloud.cfg.d/99-installer.cfg \
 /etc/cloud/ds-identify.cfg

cat > /etc/cloud/cloud.cfg.d/90_dpkg.cfg <<EOF
datasource_list: [ Azure ]
EOF

cat > /etc/cloud/cloud.cfg.d/90-azure.cfg <<EOF
system_info:
   package_mirrors:
     - arches: [i386, amd64]
       failsafe:
         primary: http://archive.ubuntu.com/ubuntu
         security: http://security.ubuntu.com/ubuntu
       search:
         primary:
           - http://azure.archive.ubuntu.com/ubuntu/
         security: []
     - arches: [armhf, armel, default]
       failsafe:
         primary: http://ports.ubuntu.com/ubuntu-ports
         security: http://ports.ubuntu.com/ubuntu-ports
EOF

cat > /etc/cloud/cloud.cfg.d/10-azure-kvp.cfg <<EOF
reporting:
  logging:
    type: log
  telemetry:
    type: hyperv
EOF
